### ISSUE TITLE
Problems with uploading technology table

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#1146]
I tried to upload an csv technology table after I added to nodes but didn't change the old ones. The old technology file was downloaded and uploaded in the new one without any editing. Did didn't work.

After calling with Joris I added the nodes manually in the technology file. Uploading the file in te existing  LES didn't work but uploading in a new LES did. In the new LES I am able to do everything in the dashboard but I cannot use the edit LES button. The ID of the new LES is 500. 
![image](https://cloud.githubusercontent.com/assets/7781037/16380655/a6572ea0-3c78-11e6-8123-6d318972b737.png)

**Comment by jorisberkhout** [comment]
Assigning @grdw to look into this with priority.

**Comment by antw** [comment]
I have already fixed this on master / beta. I'll deploy the fix to production.

**Comment by jorisberkhout** [comment]
Thanks @antw! I opened Jeroens LES (#500), but am still not able to edit it. Would you have time to look into this?

**Comment by antw** [comment]
Will do.

**Comment by jorisberkhout** [comment]
This is fixed manually by @antw . Closing this issue.

**Comment by JeroenvdLogt** [comment]
It works on my computer too. Thank you guys.
