### ISSUE TITLE
Y axis doesn't update

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1382]
![screen shot 2016-08-18 at 15 38 45](https://cloud.githubusercontent.com/assets/2676542/17775750/fb97dea0-6559-11e6-8ac3-5b6aac8ecf7e.png)

As shown in the screenshot the `gas_load` is 20kW something but the axis is stuck at 1.0. However, it does fit in the drawing which implies that the Y axis is not correctly updated.

**Comment by grdw** [comment]
Hmm.. whatever seems to be the problem is fixed by #1322 since I don't experience the same problem there.

**Comment by antw** [comment]
I think this is still broken. When the chart *first* loads, the vertical axis has the wrong numbers. Toggling any of the carriers on or off causes the axis to re-render, and then the values are correct.

![screen shot 2016-08-24 at 14 15 23](https://cloud.githubusercontent.com/assets/4383/17931871/4e5f9132-6a05-11e6-9c0f-589ab1e24d38.png)

**Comment by antw** [comment]
If I put `this.setYscaleDomain(false);` towards the end of D3LoadChart.update, that fixes it. I'm not sure if that is the correct thing to do though?

**Comment by grdw** [comment]
> If I put this.setYscaleDomain(false);

Hmm.. I'll take a closer look.. one moment.

**Comment by grdw** [comment]
I put it at the end of `render` stating that it only occurs the first time drawing. Update would trigger a recalculation everytime which is a little overkill.

**Comment by grdw** [comment]
Hmm.. and than I had to put it back at `update`. 🎊 When you switch from `total -> invididual` the Y-scale is still incorrect. But not anymore .... in 3,2,1..
