### ISSUE TITLE
I cannot edit a public LES

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1423]
I was trying to transfer a private LES from my account to another account by first making the topology and market model public and make a clone of it on the first account. After that I wanted to open the LES on the other account and clone it there to make the settings private again. However, when I clone the LES and give it a different name, I seems that it isn't saved anywhere. The new name doesn't show up anywhere. Hence I cannot edit the LES on the second account. I want to do this for two LESses namely this [LES1](https://moses.energytransitionmodel.com/testing_grounds/581) and this [LES2](https://moses.energytransitionmodel.com/testing_grounds/582).

**Comment by antw** [comment]
Sorry Thom, this should be resolved now. Let me know if you continue to have problems.

**Comment by ThomBuijs** [comment]
Thank you for the quick fix. I still have a minor issue. First I clone and edit the public LES. Afterwards I make the topology and market model private. However the cloned LES still remains visible. But I cannot open it with a different account. I guess it shouldn't be visible in the list of LESses for other accounts in the first place. The LESses I am talking about are [LES1](https://moses.energytransitionmodel.com/testing_grounds/583) and [LES2](https://moses.energytransitionmodel.com/testing_grounds/584)
