### ISSUE TITLE
Fault when opening some Buurtbatterij LESses

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1473]
When opening some older lesses on the Buurtbatterij, I get the following fault message:
![etmoses foutmelding](https://cloud.githubusercontent.com/assets/17849585/19066588/47aaa3c4-8a1a-11e6-98a7-bee88e3bbcb4.JPG)

This is the same for the LESses 'Showcase buurtbatterij - verzwaren', 'Showcase buurtbatterij -BAU', Showcase buurtbatterij -buurtbatterij'.

Can you fix this, becasue I woant to use these cases in a presentation.

@JeroenvdLogt ; @ThomBuijs  FYI

**Comment by antw** [comment]
The topologies were owned by the Quintel user and had been marked as private. Try it now @MarjoleinSchwachofer; hopefully they should be working for you again.

**Comment by MarjoleinSchwachofer** [comment]
Some now work, but 'Showcase buurtbatterij - BAU'  still doesn't work

**Comment by antw** [comment]
Sorry! I must have missed that one. It should now be fixed.

**Comment by MarjoleinSchwachofer** [comment]
yes, it now works. Thanks for the quick solution.
