### ISSUE TITLE
Unable to upload profiles from Windows computer

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#90]
I managed to upload the same curve just fine but @jeroenvandelogt gets the following errors:

* curve content-type is invalid
* curve is invalid

He has tried Mac and MS Dos encoding but to no avail.

**Comment by grdw** [comment]
You can only upload `csv` files for now. And the file itself has to be less than 100 MB.

**Comment by antw** [comment]
@ChaelKruip Assuming that it *is* a valid CSV file, is there any chance you can grab a copy of the curve file, and the internet browser (and version) in which the upload fails?

**Comment by ChaelKruip** [comment]
> Assuming that it is a valid CSV file

I thinks so. I can open it.
I can also upload it but with the current file ETLoader only 'sees' the first point it seems: [http://ivy.et-engine.com/load_profiles/266](http://ivy.et-engine.com/load_profiles/266)

> any chance you can grab a copy of the curve file

I can mail it to you. If I make a gist I'm afraid the formatting might change.

> and the internet browser (and version) 

Tried both on Chrome (v 42.0.2311.135 m) and IE9

**Comment by grdw** [comment]
OSX/Firefox
````ruby
#<ActionDispatch::Http::UploadedFile:0x007fa70437a598 
@tempfile=#<Tempfile:/var/folders/h4/qyxwrwss353djf597pzrc4_w0000gn/T/RackMultipart20150507-6279-1i6dkgg>, 
@original_filename="loadcurve_wind_offshore (1).csv", 
@content_type="text/csv", 
@headers="Content-Disposition: form-data; name=\"load_profile[curve]\"; filename=\"loadcurve_wind_offshore (1).csv\"\r\nContent-Type: text/csv\r\n">
````

Win7/Ie9
````ruby
#<ActionDispatch::Http::UploadedFile:0x007fa6f9986898 
@tempfile=#<Tempfile:/var/folders/h4/qyxwrwss353djf597pzrc4_w0000gn/T/RackMultipart20150507-6279-1yy6zh9>, 
@original_filename="loadcurve_wind_offshore (1).csv", 
@content_type="text/plain", 
@headers="Content-Disposition: form-data; name=\"load_profile[curve]\"; filename=\"loadcurve_wind_offshore (1).csv\"\r\nContent-Type: text/plain\r\n">
````

If you look at the differences between the UploadeFiles than the answer becomes clear. IE9 is seeing the file as a plain/text file instead of a csv. Why this is, is a mystery still, but I'll try to see if I can find an answer.

**Comment by grdw** [comment]
Fixed with 138506f

**Comment by ChaelKruip** [comment]
This is still an issue. I have uploaded [the offending CSV](https://www.dropbox.com/s/wu5ao4omeankzws/loadcurve%20Wind-offshore.csv?dl=0). I can upload it but the [resulting load curve](http://ivy.et-engine.com/load_profiles/296) is weird. It shows only the first value for 365 datapoints. Normally the year-view shows months but not with this CSV.
Also, the 'week-view' does not show a profile at all.

**Comment by grdw** [comment]
You can upload it :+1:  but it's weird that it produces a weird curve. I think I already saw some error passing by from Airbrake that might have something to do with it.

**Comment by antw** [comment]
> It shows only the first value for 365 datapoints.

365 means that it's only reading a single value from the curve (probably the first value). The front-end chart "expands" single-value curves to 365 values, since that's the default number of values shown in the full-year-view.

[The JSON for the load profile](http://ivy.et-engine.com/load_profiles/296.json) indeed shows only one value:

```json
"values":[0.013307981]
```

Might be an issue to do with Windows line endings. Or if the curve came from Excel, it's probably using stupid Mac OS 9 line endings like it was with our old curve files. :grimacing:

**Comment by dennisschoenmakers** [comment]
CSV line endings are always problematic. However, the client brought it back up again yesterday. :grin:

**Comment by grdw** [comment]
Yes, the thing is that it's probably easily to fix with the standard ruby `CSV` library.

But it's a mystery to me how `Paperclip` already has the `values` of the CSV available in the `Controller`, before it has even read the whole file. Is this something shady with `Paperclip` or with `Merit::Curve`? 

@antw do you know anything about this?

**Comment by grdw** [comment]
Well the only code I see is:

````ruby
def show
  respond_with(LoadProfileComponent.find(params[:id]))
end
````

And when curling (with authentication turned off), my response is:

````json
{"id":135,
"load_profile_id":364,
"curve_type":"flex",
"curve_file_name":"loadcurve_wind_offshore_(1).csv",
"curve_content_type":"text/plain",
"curve_file_size":379102,
"curve_updated_at":"2015-07-20T13:10:38.000Z",
"created_at":"2015-07-20T13:10:38.000Z",
"updated_at":"2015-07-20T13:10:38.000Z",
"values":[0.013307981] <------------
}
````

Where does the `values` attribute come from.

**Comment by grdw** [comment]
Nevermind, already found it in `CurveComponent` class.

**Comment by ChaelKruip** [comment]
@grdw what is the status of this?

**Comment by grdw** [comment]
It's already merged in master, so also in staging, and thusfar deployed.

I'll see if that's actually the case by running some tests.

**Comment by grdw** [comment]
The offending LoadProfile is now succesfully uploaded to ETMoses. So I'd say: issue closed.

**Comment by ChaelKruip** [comment]
:+1:
